# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Us8YdSBfN96txGgvvSfxVD85Ofb8TLBB
"""

import streamlit as st
from embedchain import OpenSourceApp

"""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

"""

st.title('Walks App')

def generate_response(input):
    chat_bot = OpenSourceApp()
    st.info(chat_bot.chat(input))

with st.form('my_form'):
    text = st.text_area('Enter text:', 'What are the three key pieces of advice for learning how to code?')
    submitted = st.form_submit_button('Submit')
    generate_response(text)

